Added blog post ISMIR20, Ruchit
mip-frontiers/mip-frontiers.github.io pull request #24
Opened 2020-12-07 12:59 UTC by rragrawal

Blog post about a paper from ISMIR 2020.

2020-12-15 09:21 UTC, furkanyesiler requested changes
Some minor work needed.

2020-12-15 09:21 UTC, furkanyesiler commented on _posts/2020-12-02-sf_ismir20.md
> +This year's ISMIR was held virtually, following the trend of online conferences smitten by the COVID-bug.  I attended [ISMIR 2020](https://www.ismir2020.net/), the 21<sup>st</sup> International Socie
Fix the mixed "capital - non-capital" situation for the paper title.

2020-12-15 09:21 UTC, furkanyesiler commented on _posts/2020-12-02-sf_ismir20.md
> +This year's ISMIR was held virtually, following the trend of online conferences smitten by the COVID-bug.  I attended [ISMIR 2020](https://www.ismir2020.net/), the 21<sup>st</sup> International Socie
I.e., "Learning to read and Follow music in Complete score sheet images"

2020-12-15 09:21 UTC, furkanyesiler commented on _posts/2020-12-02-sf_ismir20.md
> +The basic idea is motivated by “referring image segmentation” (cite), a task in computer vision that aims to identify a region in an image, given a language expression as the query. To better underst
I assume you took a personal note with "(cite)". Please complete that citation.

2020-12-15 09:21 UTC, furkanyesiler commented on _posts/2020-12-02-sf_ismir20.md
> +  Referring image segmentation. Figure from [^3]
The citation [^3] doesn't work in the caption. I'm not sure if it's possible to fix it.

2020-12-15 09:21 UTC, furkanyesiler commented on _posts/2020-12-02-sf_ismir20.md
> +The basic idea is motivated by “referring image segmentation” (cite), a task in computer vision that aims to identify a region in an image, given a language expression as the query. To better underst
And maybe finish the last sentence with ":".

2020-12-15 09:21 UTC, furkanyesiler commented on _posts/2020-12-02-sf_ismir20.md
> +  The FiLM layer used before the last activation [^4]
The citation [^4] doesn't work here either.

2020-12-17 06:35 UTC, rragrawal commented
Fixed the typos and other minor issues.

2020-12-17 06:36 UTC, merged